app/models.py
from . import db
from flask_login import UserMixin, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager
from sqlalchemy.sql import func


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    pass_secure = db.Column(db.String(128), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)
    comments = db.relationship('Comment', backref='author', lazy=True)

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)


def __repr__(self):
        return f'User {self.username}'


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_post(cls):
        posts = Post.query.all()
        return posts

    def __repr__(self):
        return f"Post('{self.content}')"


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Comment('{self.content}')"


class Quote:
    def __init__ (self,author,quote):
        self.author = author
        self.quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, PasswordField, BooleanField, RadioField
from wtforms.validators import Required, Email, EqualTo
from wtforms import ValidationError
from flask_login import current_user
from app.models import User



# class RegistrationForm(FlaskForm):
#     username = StringField('Username',
#                            validators=[DataRequired(), Length(min=2, max=20)])
#     email = StringField('Email',
#                         validators=[DataRequired(), Email()])
#     password = PasswordField('Password', validators=[DataRequired()])
#     confirm_password = PasswordField('Confirm Password',
#                                      validators=[DataRequired(), EqualTo('password')])
#     submit = SubmitField('Sign Up')
#
#     def validate_username(self, username):
#         user = User.query.filter_by(username=username.data).first()
#         if user:
#             raise ValidationError('That username is taken. Please choose a different one.')
#
#     def validate_email(self, email):
#         user = User.query.filter_by(email=email.data).first()
#         if user:
#             raise ValidationError('That email is taken. Please choose a different one.')
#

class PostForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('Content', validators=[Required()])
    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    content = TextAreaField('Content', validators=[Required()])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_simplemde import SimpleMDE
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()

db = SQLAlchemy()
simple = SimpleMDE()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    simple.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Registering auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
from flask_bootstrap import Bootstrap

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for, flash
from . import main
from flask_login import login_required, current_user

from ..auth.forms import RegistrationForm
from ..models import Post, User, Comment
from .forms import CommentForm, PostForm
from flask.views import View, MethodView
from .. import db
from app import requests
import markdown
from .. import requests


# views
@main.route('/', methods=['GET', 'POST'])
@main.route("/index")
def index():
    """"""
    page = request.args.get('page', 1, type=int)

    return render_template('index.html')


@main.route('/posts/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        description = form.content.data
        title = form.title.data

        print(current_user._get_current_object().id)
        new_post = Post(author=current_user, title=title, content=description)
        db.session.add(new_post)
        db.session.commit()

        return redirect(url_for('main.index'))
    return render_template('posts.html', form=form)


@main.route("/quote")
def about():
    quote = requests.get_quote()
    return render_template('quote.html', title='About', quote=quote)


@main.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)

@main.route("/quotes")
def quote():
    quote = requests.get_quote()
    return render_template('quote.html',quote=quote)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{%block styles%}

{{ simplemde.css }}
{{ simplemde.js }}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}



<!--navbar-->
{% block navbar %}

    {% include 'navbar.html' %}

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content %}

    <title> {{ title }} </title>

    <div class="container">
        <h1> ERROR PAGE</h1>

    </div>

{% endblock %}

app/templates/home.html
{% extends 'bootstrap/base.html' %}
{% import 'macros.html' as macro %}
{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}

{% block content %}

app/templates/index.html
{% extends 'base.html'%}
{% block content %}

 {{super ()}}

<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles.css')}}">
<div class="container-fluid welcome-page">
    <div class="container">
        <div class="home">
                <h1>BLOG POST</h1>
             <div class="row">


            <div class="col-md-4 welcome">
                <br><br><br>
                <p>Have a story worth sharing? You can now create your own blog post.<br> Just click the button below</p>
                  <button class=" btn"><a href="{{url_for('main.new_post')}}">ADD POST</a></button>

            </div>

            <div class="col-md-8 welcome">
                <br><br>
                {% for pitch in pitches %}
                <h3><u>{{post.title}}</u></h3>
                    <p>{{post.description}}</p>
                    <hr>
                {% endfor %}

            </div>
        </div>



        </div>

    </div>

</div>

{% endblock %}

app/templates/navbar.html
 <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a href="/">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>

    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">

                    <li class="nav-link"><a href="{{url_for('auth.login')}}">Sign in</a></li>
                    <li class="nav-link"><a href="{{url_for('main.quote')}}">Quotes</a></li>


      </ul>
    </div>
  </div>
</nav>

app/templates/posts.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% include 'navbar.html'%}




{% block content %}
<div class="container">
	<div class="row">
		<div class="jumbotron">
				{{wtf.quick_form(form)}}
		<ul style="list-style: none;">
				{% for post in posts %}
					<div class="list-group">
						<a href="#">
							<div class="list-item">
								<p>{{post.id}}</p>
							</div>
							<h4>{{ post.description }}</h4>
							<h6> Posted by {{user.username}}.</h6>
						</a>
					</div>
				{% endfor %}
		</ul>
		</div>
	</div>
</div>


{% endblock %}

app/templates/quote.html
{% extends "base.html" %}
{% block content %}
<blockquote class="quote-box text-center primary-color">
      <p class="quotation-mark">
        “
      </p>
    <br><br><br>
      <p class="quote-text">
        {{quote.quote}}
      </p>
      <hr />
      <div class="blog-post-actions">
        <p class="blog-post-bottom pull-left">
          {{quote.author}}
        </p>
      </div>
    </blockquote>
{% endblock content %}